name: Run LPPLCI Daily at 9AM KST

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 기준 → KST 오전 9시
  workflow_dispatch:      # 수동 실행도 가능하게 설정

jobs:
  run-lpplci:
    runs-on: ubuntu-latest

    env:
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LPPLCI script
        run: python test_lpplci.py
